### ISSUE TITLE
missing title error in penn data

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#129]
I can figure out why the title is missing once https://github.com/sul-dlss/dlme-transform/issues/128 is resolved.

**Comment by jacobthill** [comment]
Need to take a look at the values with missing titles and decide wether to delete the records or pass the default value in the traject config of `title not provided'

**Comment by anarchivist** [comment]
So, taking brief look at these, there appear to be only 2 records in the Egyptian collections and 9 in the Near Eastern collections that have no title. My inclination is that we should skip these records because the information is not super useful in own right. For example, it's not clear what kind of objects these are, and even on the Penn Museum site, there aren't thumbnails. I think we can figure out a way to skip these records in the Traject mapping but you might want to check with the team.

**Comment by anarchivist** [comment]
Here's the code that should go into the Penn Museum mappings to skip the records that don't have the title info (cc @peetucket)

```ruby
each_record do |record, context|
  context.skip!('Missing title') if record['object_name'].nil?
end
```
