### ISSUE TITLE
Analyze Sakip Sabanci dates

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#258]
These are oai_dc records.  There are 4? collections within Sakip.  It may be easier to parse them separately, if the patterns within collections differ from other collections.  Other oai_dc collections, should that matter (unlikely) are AU Cairo and harvard ihp.

Tasks:
- [ ] Identify any valid patterns
- [ ] Identify any patterns that can be ignored
- [ ] Identify any patterns that should raise an error 

And:
- [ ] determine if valid patterns are handled by existing macros
- [ ] determine if individual collection dates are more easily parsed separately from other collections

**Comment by jacobthill** [comment]
## sakip-sabanci/abidindino:
- 1970-11-17
- [1988].
- 22.02.1996. 
- 1960\.
- Paris
- [195?].
- [n.d.]

Most are dates in the top four forms. 'Paris' and '[n.d.]' should be ignored. There is consistency in the . separator and the - separator; the first is always day-month-year and the latter is always year-month-day. A strategy could be to
1. remove trailing periods
2. if dashes present grab first four digits
3. if periods present grab last four digits
4. ignore string with no digits (this could be a generic algorithm; I imagine it will be useful elsewhere)
5. ignore [n.d.] (this could also be part of a generic undated method)
6. Deal with [195?]. (I interpret it as 1950-1959
7. the rest should be four digit years

## sakip-sabanci/emirgan: 

all dates are either four digit years or in the form '1912/1913' or '1931-1932'. In the case there are two four digit years separated by a / or -, the second year is always one larger than the first.

## sakip-sabanci/ResimKlksyn: 
- Mostly four digit years, '1938'
- four digit year with parenthesis and ? e.g. 1938 (?)
- two year range e.g. '1914-15'
- Century string e.g. '20. yüzyıl' which means 20th century (this is the only pattern for centuries)
- 189x (I assume this means 1890's) 
- 1955 civarı (meaning approximately 1955)

If first four characters are numbers and fifth character is a space -> pass those characters through as the date.

If first four characters are numbers and fifth character is a dash -> pass first four characters through and plus one (e.g '1914-15' becomes [1914, 1915]

There is only one case of 189x -> convert this to decade 1890-1899 array

There are three cases of '20. yüzyıl' -> match this string and convert to 1900-1999 array

## sakip-sabanci/KitapVehat:

This is the fun one!

- 998 H (1590 M)
- 1101 H (1689-1690 M)
- 1335 civarı
- 17\. yüzyıl başı
- 16\. - 17\. yüzyıl
- 18\. yüzyılın ortaları
- 1085 H
- 19\. yüzyılın ikinci yarısı
- muhtemelen 1790 civarı
- 1958
- Tarihsiz (meaning undated)
- muhtemelen 1809-1810 sonrası (meaning probably after 1809-1810)
- 1269, 1272, 1273 H

Due to the large variation in strings of Turkish language dates, I would recommend ignoring these for now. One strategy could be to:
1. look for four digits followed by a space and capital H -> grab the four digits and pass to hijri_to_gregorian method
2. If no H pass four digits as a Gregorian year
3. deal with this '1269, 1272, 1273 H'
4. ignore the rest for now

**Comment by ndushay** [comment]
Let's talk through what is needed before running with what I wrote above. The patterns are valid -- it's the "what is the best way to get the date range" that might have changed, as a bunch of these patterns are now handled by ParseDate.range_array.

**Comment by ndushay** [comment]
@jacobthill what should I do when there are multiple values that disagree?

e.g.  ResimKlksyn-463.xml has:

```xml
<dc:date>20. yüzyıl</dc:date>
<dc:date>1913</dc:date>
<dc:date>1993</dc:date>
and later:
<dc:date>2008</dc:date>
```

**Comment by ndushay** [comment]
#### Kitapvehat

```
oai:cdm21044.contentdm.oclc.org:Kitapvehat/103901	887 H (1482 M)|1482|1482|2002
oai:cdm21044.contentdm.oclc.org:Kitapvehat/103928	1085 H (1674 M)|1674|1674|2002
oai:cdm21044.contentdm.oclc.org:Kitapvehat/127434	18. yüzyıl|1700|1799
oai:cdm21044.contentdm.oclc.org:Kitapvehat/133173	1288 H (1871 M)|1871|1871
oai:cdm21044.contentdm.oclc.org:Kitapvehat/133194	16. yüzyıl|1500|1520|2002

```

**Comment by ndushay** [comment]
PR is up;  closing this analysis ticket.
