### ISSUE TITLE
Check, revise, and transform Michigan

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#351]
After significant changes to the IR, it is necessary to check, possibly revise, re-transform, and re-load the Michigan data sets.

**Comment by jacobthill** [comment]
@ndushay should this be closed? I can't remember but I thought you finished this one.

**Comment by ndushay** [comment]
@jacobthill - I was thinking you'd like to look at the data and see if you're ok with what I did ...

**Comment by jacobthill** [comment]
@ndushay I did look at the data and it seems ok except some of the language values which were not caused by your work. I fixed those and It seems ok now. I will close it for now. I want to revisit many of the collections when things slow down, including this one so I will leave the old config file there until I get a chance to do that.
