### ISSUE TITLE
Upgrade all dependencies

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#705]
One of the requirements of transferring hosting of DLME to QNL is that all dependencies are up-to-date. For the web application this means a new version of Spotlight and Mirador. There is an open ticket to upgrade to the latest version of traject: https://github.com/sul-dlss/dlme-transform/issues/230. Do we need to upgrade other libraries? Do we need a new release of traject plus?

**Comment by aaron-collier** [comment]
Aside from #230 are there any updates not already covered by weekly updates for infrastucture?

I'm wondering if this should be more about documenting the update process for handoff.

**Comment by aaron-collier** [comment]
Also, aside from ActiveSupport, Thor, and traject_plus, we only pin dependencies (https://github.com/sul-dlss/dlme-transform/blob/main/Gemfile#L21) in the test group, meaning they aren't deployed or included in the production build. We typically pin things like `rubocop` so that weekly updates are not significantly effected by changes and additions to cops. We can certainly updates those pins but removing them should really include some documentation/training on expectations for hand off.
