### ISSUE TITLE
Bad thumbnails in QNL

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#758]
A few QNL records have bad thumbnails leading to pages that will not render in the application: 
 
- https://app.honeybadger.io/projects/53082/faults/80088751/01FB4G4F3PB8QZT061807CR2C0#notice-summary

- For example, we can draw this page: https://dlmenetwork.org/ar/library/catalog?f%5Bdate%5D%5B%5D=1400&page=12565

- but not this one: https://dlmenetwork.org/ar/library/catalog?f%5Bdate%5D%5B%5D=1400&page=12561

Known bad ids are:

- 81055/vdc_100023618815.0x000007 from record  [qnl/british-library-combined/data/group7/qnl-combined-6815.xml](https://github.com/sul-dlss/dlme-metadata/blob/main/qnl/british-library-combined/data/group7/qnl-combined-6815.xml)
- 81055/vdc_100023618815.0x000005 from record [qnl/british-library-combined/data/group17/qnl-combined-16488.xml](https://github.com/sul-dlss/dlme-metadata/blob/main/qnl/british-library-combined/data/group17/qnl-combined-16488.xml)
- 81055/vdc_100076686717.0x000001
- 81055/vdc_100023618815.0x00000d
- 81055/vdc_100038750373.0x000002
- 81055/vdc_100000000193.0x0000bc

The raw data from the provider has e.g. "https://images.qdl.qa/iiif/images/81055/vdc_100023281998.0x000001/Photo 355_1_0013.jp2/full/!1000,1000/0/default.jpg" in the preview field (the other record has the same pattern).

Need to:

- [ ] reharvest QNL
- [ ] see if the data is the same and revise mapping config, if needed

**Comment by aaron-collier** [comment]
@jacobthill at least part of the issue is a bug in the QNL transform:

https://github.com/sul-dlss/dlme-transform/blob/main/traject_configs/qnl_config.rb#L152

here, if there isn't a iiif_manifest we insert the ID into `agg_preview.wr_id` and not a formatted URL, this is why you see the id based pattern above and not a URL. 

Should we update the transform to inject a standard/generic thumbnail URL? Or not include this particular field? I'm not sure what the implications of that would be in the UI however.

**Comment by aaron-collier** [comment]
My suggestion, since the `agg_preview.wr_id` field is the thumbnail field used in blacklight here (https://github.com/sul-dlss/dlme/blob/main/app/controllers/catalog_controller.rb#L63) and a default thumbnail is available, we add a validation at the above point (and any other collections that may need it) that then does not include the `agg_preview.wr_id` if it is not a valid URL.

I'm going to run a test or two in dev.

**Comment by jacobthill** [comment]
Yeah, I saw the error in the config, but there is an error in the raw data files as well. We can fix the config to ignore the iiif manifest in those cases and grab the url from the raw data but it won't actually fix these urls until QNL updates them and we re-harvest. 

I'm not sure we want to display our image placeholder if the thumbnail is not valid. I think we want to suppress the record once we have the auto harvest worked out. In that case if the url breaks, we will not reload it and it the provider fixes the error the record will get loaded on the next auto harvest. Does that make sense?
