### ISSUE TITLE
Investigate duplication of output

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#931]
Using AIMS as an example, comparing the harvested record count (145) to the transformed record count (290) there is obvious duplication. We'll need to investigate if this is a bug in our code, traject, or traject plus.

**Comment by jmartin-sul** [comment]
note: https://github.com/sul-dlss/dlme-airflow/pull/279 adds a basic validation of the transformation output by comparing the count of harvested records in the dataframe Intake produces to the count of ndjson records dlme-transform produced from the CSV that the dataframe was saved to.  that validation works around the duplication noted in this issue, so if/when this is resolved, we'll want to undo that workaround.  the workaround is currently implemented in `dlme_airflow/tasks/transform_validation.py` (`tests/tasks/test_transform_validation.py` will also be affected since the test has to simulate this issue to properly test the workaround).

**Comment by jmartin-sul** [comment]
didn't seem to be occurring in AWS, so dlme-airflow workaround was undone in https://github.com/sul-dlss/dlme-airflow/pull/303
